package com.example.cross_platformfilemanager.ui.theme

import androidx.compose.runtime.Immutable
import androidx.compose.ui.graphics.Brush
import androidx.compose.ui.graphics.Color

@Immutable
data class TaggoColors(
    val appBackground: Color,
    val surface: Color,
    val surfaceElevated: Color,
    val surfaceVariant: Color,
    val surfaceSelected: Color,
    val panelBackground: Color,
    val panelBackgroundSoft: Color,
    val panelBorder: Color,
    val panelHighlight: Color,
    val border: Color,
    val borderStrong: Color,
    val primaryAccent: Color,
    val primaryAccentSoft: Color,
    val textPrimary: Color,
    val textSecondary: Color,
    val textMuted: Color,
    val danger: Color,
    val success: Color,
    val warning: Color,
    val backgroundBrush: Brush,
    val dashboardBackground: Color,
    val dashboardPanelBackground: Color,
    val dashboardPanelBorder: Color,
    val dashboardItemBackground: Color,
    val dashboardItemBorder: Color,
    val dashboardBadgeBackground: Color,
    val dashboardBadgeText: Color,
    val dashboardAccent: Color,
    val dashboardProgressTrack: Color,
    val dashboardProgressFill: Color,
    val dashboardProgressFillImage: Color,
    val dashboardProgressFillVideo: Color,
    val dashboardProgressFillAudio: Color,
)

internal fun defaultTaggoColors(): TaggoColors =
    TaggoColors(
        appBackground = Color(0xFF0F1117),
        surface = Color(0xFF151922),
        surfaceElevated = Color(0xFF1C222D),
        surfaceVariant = Color(0xFF222936),
        surfaceSelected = Color(0xFF2A2342),
        panelBackground = Color(0xEE1A1F28),
        panelBackgroundSoft = Color(0xC0131720),
        panelBorder = Color(0x80404A5D),
        panelHighlight = Color(0x24F7F9FF),
        border = Color(0xFF2A2E37),
        borderStrong = Color(0xFF3B4252),
        primaryAccent = Color(0xFF7C5CFF),
        primaryAccentSoft = Color(0xFF2B235A),
        textPrimary = Color(0xFFF2F4F8),
        textSecondary = Color(0xFFB2BBCB),
        textMuted = Color(0xFF8690A0),
        danger = Color(0xFFFF5C7A),
        success = Color(0xFF43D17A),
        warning = Color(0xFFF5B84B),
        backgroundBrush = Brush.verticalGradient(
            colors = listOf(
                Color(0xFF11141B),
                Color(0xFF0F1117),
                Color(0xFF0C0E13),
            ),
        ),
        dashboardBackground = Color(0xFF080811),
        dashboardPanelBackground = Color(0xE610111D),
        dashboardPanelBorder = Color(0x802B2346),
        dashboardItemBackground = Color(0xE617192A),
        dashboardItemBorder = Color(0x802B2346),
        dashboardBadgeBackground = Color(0xFF242447),
        dashboardBadgeText = Color(0xFFCFCBFF),
        dashboardAccent = Color(0xFF8B5CFF),
        dashboardProgressTrack = Color(0xFF23253A),
        dashboardProgressFill = Color(0xFF8B5CFF),
        dashboardProgressFillImage = Color(0xFF6E7DFF),
        dashboardProgressFillVideo = Color(0xFFD95FFF),
        dashboardProgressFillAudio = Color(0xFFFF9A57),
    )
